- name: install mariadb in Ubuntu
  tags: db, mariadb, ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb server in CentOS
  tags: db, mariadb, centos
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"